on: [push]

name: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # needed for C to build
      - name: Install package
        run: |
          sudo apt-get -y install gnulib

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build code
        uses: actions-rs/cargo@v1
        with:
          command: build